# Generated by Django 5.2.5 on 2025-09-28 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_profile_email_profile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='customer.customer'),
        ),
    ]
