# Generated by Django 5.2.5 on 2025-09-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel',
            new_name='hotel_id',
        ),
    ]
