# Generated by Django 5.2.5 on 2025-09-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_address_booking_payment_status_booking_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='booking_images'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
