# Generated by Django 5.2.5 on 2025-09-20 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='advance_amount',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='booking.booking'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_address', to='booking.booking'),
        ),
    ]
