# Generated by Django 5.2.5 on 2025-09-20 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_payment_amount_payment_advance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.TextField(),
        ),
    ]
