# Generated by Django 5.2.5 on 2025-09-20 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_payment_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='payments_booking', to='booking.booking'),
        ),
    ]
