# Generated by Django 5.2.5 on 2025-09-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
