# Generated by Django 5.2.5 on 2025-09-21 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_payment_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
