# Generated by Django 5.2.5 on 2025-08-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotal_name', models.CharField(max_length=25, unique=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='hotel_images')),
                ('description', models.CharField()),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amentities', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'Hotel',
                'ordering': ['-id'],
            },
        ),
    ]
