# Generated by Django 5.2.5 on 2025-08-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_alter_hotal_description_hotelmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotal',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotal',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
