# Generated by Django 5.2.5 on 2025-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_hotal_is_active_hotal_phone_hotal_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='slider_images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'db_table': 'Hotel_slider',
                'ordering': ['-id'],
            },
        ),
    ]
