# Generated by Django 5.2.5 on 2025-09-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotal',
            old_name='amentities',
            new_name='amenities',
        ),
        migrations.AlterField(
            model_name='hotal',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
