# Generated by Django 5.2.5 on 2025-09-15 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_rename_amentities_hotal_amenities_alter_hotal_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelmanager',
            old_name='hotel',
            new_name='hotel_id',
        ),
    ]
