# Generated by Django 5.2.5 on 2025-09-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_rename_hotel_hotelmanager_hotel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelmanager',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
