# Generated by Django 5.2.5 on 2025-09-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0007_rename_hotel_id_hotelmanager_hotel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hotal',
            name='manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HotelManager',
        ),
    ]
