# Generated by Django 5.2.5 on 2025-09-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0008_hotal_manager_delete_hotelmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotal',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
