# Generated by Django 5.0.7 on 2025-11-27 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_create_admin'),
        ('user', '0003_user_is_admin'),
    ]

    operations = [
    ]
